class_name CONSTANTS extends Node

enum MOVEMENT_STATUS {DOWN, WAIT, UP}

const CHARACTER_MOVEMENT_ANIMATIONS_IDLE = "idle"
const CHARACTER_MOVEMENT_ANIMATIONS_CLIMB = "climb"
const CHARACTER_MOVEMENT_ANIMATIONS_WALK = "walk"
const CHARACTER_MOVEMENT_ANIMATIONS_JUMP = "jump"
const CHARACTER_MOVEMENT_ANIMATIONS_HURT = "hurt"

const GROUPS_PLAYER = "player"
const GROUPS_ENEMY = "enemy"
const GROUPS_WALL = "wall"

const ENEMY_BULLET_COLOR = "#E85C0D"
const PLAYER_BULLET_COLOR = "#FABC3F"
